[package]
name = "hello"
version = "0.1.0"
authors = ["tomoyuki-nakabayashi <tomo.wait.for.it.yuki@gmail.com>"]

[dependencies]
linked_list_allocator = { path="../../linked-list-allocator" , default-features=false }

[build-dependencies]
cc = "1.0.25"

[features]
alloc_error_handler=[]
